{{- if .Values.enabled }}
{{- $secret := dict "name" ( printf "%s-%s" (include "postgres-cluster.fullname" $ ) "config" ) }}
{{- $labels := include "postgres-cluster.labels" $ | fromYaml }}
{{- $secret = set $secret "parsers" .Values.parsers }}
{{- $secret = set $secret "service" .Values.configs }}
{{- $secret = set $secret "inputs" .Values.inputs }}
{{- $secret = set $secret "filters" .Values.filters }}
{{- $secret = set $secret "outputs" .Values.outputs }}
{{- $secret = set $secret "annotations" .Values.annotations }}
{{- include "fluentbit.secret" (list $ $labels $secret ) }}
{{- end }}
