{{- if .Values.enabled }}
{{- $parsers := .Values.parsers }}
{{- $service := .Values.service }}
{{- $inputs := .Values.inputs }}
{{- $filters := .Values.filters }}
{{- $outputs := .Values.outputs }}
{{- $labels := include "fluentbit.labels" $ | fromYaml }}
{{- $name := printf "%s-%s" (include "fluentbit.fullname" $ ) "config" }}
{{- include "fluentbit.secret" (list $ $labels $name $parsers $service $inputs $filters $outputs ) }}
{{- end }}
