{{- range $name, $secret := .Values.secrets }}
{{- $labels := include "fluentbit.labels" $ | fromYaml }}
{{- $secret = set $secret "name" ( printf "%s-%s" (include "fluentbit.fullname" $ )  $name ) }}
{{- include "fluentbit.secret" (list $ $labels $secret ) }}
{{- end }}
