apiVersion: v2
name: gl-runner
version: 0.2.6

dependencies:
  # https://gitlab.com/gitlab-org/charts/gitlab-runner
  - name: gitlab-runner
    version: 0.84.2
    repository: https://charts.gitlab.io
    alias: gl-runner
    condition: gl-runner.enabled

