apiVersion: v2
name: konghq
version: 1.0.0
appVersion: "3.9"
dependencies:
  - name: certificates
    version: 0.1.0
    repository: file://../chart_deps/security/certificates
    alias: certificates
    condition: certificates.enabled
  - name: kong-plugins
    version: 0.1.0
    repository: file://../chart_deps/konghq/plugins
    alias: kong-plugins
    condition: kong-plugins.enabled
  #https://github.com/Kong/charts/blob/main/charts/kong
  - name: kong
    version: 3.0.1
    repository: https://charts.konghq.com
    alias: kong
    condition: kong.enabled
