apiVersion: v2
name: gha-runner
version: 0.1.0
dependencies:
  #https://github.com/actions/actions-runner-controller/tree/master/charts/gha-runner-scale-set
  - name: gha-runner-scale-set
    version: 0.12.1
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    alias: gha-runner
    condition: gha-runner.enabled
