apiVersion: v2
appVersion: 2.16.1
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: The RabbitMQ Cluster Kubernetes Operator automates provisioning, management,
  and operations of RabbitMQ clusters running on Kubernetes.
name: rabbitmq-cluster-operator
version: 0.1.0
