apiVersion: v2
appVersion: "1.0"
description: Chart for fluentbit operated
name: fluentbit-operated
version: 0.1.0

dependencies:
  - name: fluentbit-lib
    version: 0.1.0
    repository: file://../lib
  - name: core
    version: 0.1.0
    repository: file://../../../app/core
  - name: prometheus-lib
    version: 0.1.0
    repository: file://../../../prometheus/lib
