apiVersion: v2
appVersion: "1.0"
description: helm chart for creating postgres clusters using zolando postgres operator
name: postgres-cluster
version: 0.1.0

dependencies:
  - name: core
    version: 0.1.0
    repository: file://../../app/core
