apiVersion: v2
name: gha-operator
version: 0.1.0
dependencies:
  #https://github.com/actions/actions-runner-controller/tree/master/charts/gha-runner-scale-set-controller
  - name: gha-runner-scale-set-controller
    version: 0.13.1
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    alias: gha-operator
    condition: gha-operator.enabled
