{{- if .Values.fluentbit.enabled }}
{{- range $name, $secret := .Values.secrets }}
{{- $labels := include "postgres-cluster.labels" $ | fromYaml }}
{{- $secret = set $secret "name" ( printf "%s-%s" (include "postgres-cluster.fullname" $ )  $name ) }}
{{- include "core.secret" (list $ $labels $secret ) }}
{{- end }}
{{- end }}
