{{- if .Values.fluentbit.enabled }}
{{- $secret := dict "name" ( printf "%s-%s" (include "postgres-cluster.fullname" $ ) "fluentbit-config" ) }}
{{- $labels := include "postgres-cluster.labels" $ | fromYaml }}
{{- $secret = set $secret "parsers" .Values.fluentbit.parsers }}
{{- $secret = set $secret "service" .Values.fluentbit.service }}
{{- $secret = set $secret "inputs" .Values.fluentbit.inputs }}
{{- $secret = set $secret "filters" .Values.fluentbit.filters }}
{{- $secret = set $secret "outputs" .Values.fluentbit.outputs }}
{{- $secret = set $secret "annotations" .Values.fluentbit.annotations }}
{{- include "fluenbit.secret" (list $ $labels $secret ) }}
{{- end }}
