apiVersion: v2
name: argocd
version: 1.0.0
dependencies:
  #https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
  - name: argo-cd
    version: 9.1.7
    repository: https://argoproj.github.io/argo-helm
    alias: argocd
    condition: argocd.enabled
  - name: certificates
    version: 0.1.0
    repository: file://../chart_deps/security/certificates
    alias: certificates
    condition: certificates.enabled
  - name: redis-operated
    version: 0.1.0
    repository: file://../chart_deps/redis/redis-operated
    alias: redis
    condition: redis.enabled
  - name: probes
    version: 0.1.0
    repository: file://../chart_deps/prometheus/probes
    alias: probes
    condition: probes.enabled
  - name: core
    version: 0.1.0
    repository: file://../chart_deps/app/core
