apiversion: v2
name: rabbitmq
version: 0.1.0
dependencies:
  - name: rabbitmq-cluster
    version: 0.1.0
    repository: file://../chart_deps/rabbitmq/rabbitmq-cluster/
    alias: rabbitmq-main
    condition: rabbitmq-main.enabled
  #https://github.com/bitnami/charts/tree/rabbitmq-cluster-operator/4.4.37/bitnami/rabbitmq-cluster-operator
  - name: rabbitmq-cluster-operator
    version: 0.1.0
    repository: file://../chart_deps/rabbitmq/rabbitmq-cluster/
    alias: rabbitmq-cluster-operator
    condition: rabbitmq-cluster-operator.enabled
  - name: core
    version: 0.1.0
    repository: file://../chart_deps/app/core
